name: Vercel Preview Deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches:
      - main  

jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "yarn"


      - name: Install Dependencies
        run: yarn install --immutable


      - name: Configure Vercel
        run: |
          yarn vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
          cp .vercel/.env.preview.local .env
          

          echo '${{ secrets.SUPABASE_CRT }}' > ./supabase.crt
          echo 'NODE_EXTRA_CA_CERTS=./supabase.crt' >> .env
          
 
          yarn zenstack generate
          yarn prisma generate
          

          yarn prisma migrate deploy


      - name: Build Project
        run: yarn vercel build --token=${{ secrets.VERCEL_TOKEN }}

    
      - name: Deploy to Vercel
        run: |
          yarn vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} > deploy.log
          

          DEPLOY_URL=$(grep -o 'https://[^ ]*\.vercel\.app' deploy.log | head -n1)
          
          yarn vercel alias set $DEPLOY_URL alinhu1-todolist.vercel.app \
            --scope $VERCEL_ORG_ID \
            --token=${{ secrets.VERCEL_TOKEN }}